Repository sphamba/smear-cursor.nvim, pull requests merged in 2024-12, with the labels that each got.

#35 feat: add SmearToggle command
  lua/smear_cursor/init.lua
Labels: enhancement

#45 fix: add buffer filetype for filtering
  lua/smear_cursor/draw.lua
Labels: bug

#46 fix: invalid window id
  lua/smear_cursor/config.lua
  lua/smear_cursor/draw.lua
Labels: bug

#52 feat: better quad edges
  lua/smear_cursor/config.lua
  lua/smear_cursor/draw.lua
Labels: enhancement

#56 fix: reduce bulging
  lua/smear_cursor/config.lua
  lua/smear_cursor/draw.lua
  tests/test.lua
  tests/test_draw_quad.lua
Labels: bug

#57 perf: add max smear length
  lua/smear_cursor/animation.lua
  lua/smear_cursor/config.lua
Labels: performance

#58 fix: lag due to too many draws
  lua/smear_cursor/animation.lua
  tests/test.lua
Labels: performance

#59 feat: add list of filetypes where smear is disabled
  lua/smear_cursor/config.lua
  lua/smear_cursor/events.lua
Labels: enhancement

#63 fix: smear on zz zt zb movements
  lua/smear_cursor/animation.lua
Labels: bug

#70 fix: restore "none" cursor_color processing
  lua/smear_cursor/color.lua
Labels: bug

#77 feat: add parameter to enable/disable smear to cmd line
  lua/smear_cursor/config.lua
  lua/smear_cursor/events.lua
Labels: enhancement
