Repository sphamba/smear-cursor.nvim, pull requests merged in 2025-01, with the labels that each got.

#84 feat: add minimum smear activation distances
  README.md
  lua/smear_cursor/animation.lua
  lua/smear_cursor/config.lua
Labels: enhancement

#89 fix: possible NaN corners
  lua/smear_cursor/animation.lua
Labels: bug

#92 feat: smear to noice.nvim command_palette
  lua/smear_cursor/screen.lua
Labels: enhancement

#93 feat: add arbitrary key press detection
  lua/smear_cursor/config.lua
  lua/smear_cursor/events.lua
Labels: enhancement

#94 perf(events): register autocmds using lua api
  lua/smear_cursor/events.lua
Labels: performance

#95 fix: noice.nvim getting cmdline_pos results in nil value
  lua/smear_cursor/screen.lua
Labels: bug
